module.exports = {
    purge: {
        mode: 'all',
        content: ['./public/**/*.html'],
    },
    theme: {
        borderRadius: {
            'none': 'var(--border-radius-none)',
            'sm': 'var(--border-radius-sm)',
            'DEFAULT': 'var(--border-radius)',
            'md': 'var(--border-radius-md)',
            'lg': 'var(--border-radius-lg)',
            'xl': 'var(--border-radius-xl)',
            '2xl': 'var(--border-radius-2xl)',
            '3xl': 'var(--border-radius-3xl)',
            'full': 'var(--border-radius-full)',
        },
        textColor: {
            black: 'var(--color-text-black)',
            white: 'var(--color-text-white)',
            gray: {
                50: 'var(--color-text-gray-50)',
                100: 'var(--color-text-gray-100)',
                200: 'var(--color-text-gray-200)',
                300: 'var(--color-text-gray-300)',
                400: 'var(--color-text-gray-400)',
                500: 'var(--color-text-gray-500)',
                600: 'var(--color-text-gray-600)',
                700: 'var(--color-text-gray-700)',
                800: 'var(--color-text-gray-800)',
                900: 'var(--color-text-gray-900)',
            },
            red: {
                50: 'var(--color-text-red-50)',
                100: 'var(--color-text-red-100)',
                200: 'var(--color-text-red-200)',
                300: 'var(--color-text-red-300)',
                400: 'var(--color-text-red-400)',
                500: 'var(--color-text-red-500)',
                600: 'var(--color-text-red-600)',
                700: 'var(--color-text-red-700)',
                800: 'var(--color-text-red-800)',
                900: 'var(--color-text-red-900)',
            },
            yellow: {
                50: 'var(--color-text-yellow-50)',
                100: 'var(--color-text-yellow-100)',
                200: 'var(--color-text-yellow-200)',
                300: 'var(--color-text-yellow-300)',
                400: 'var(--color-text-yellow-400)',
                500: 'var(--color-text-yellow-500)',
                600: 'var(--color-text-yellow-600)',
                700: 'var(--color-text-yellow-700)',
                800: 'var(--color-text-yellow-800)',
                900: 'var(--color-text-yellow-900)',
            },
            green: {
                50: 'var(--color-text-green-50)',
                100: 'var(--color-text-green-100)',
                200: 'var(--color-text-green-200)',
                300: 'var(--color-text-green-300)',
                400: 'var(--color-text-green-400)',
                500: 'var(--color-text-green-500)',
                600: 'var(--color-text-green-600)',
                700: 'var(--color-text-green-700)',
                800: 'var(--color-text-green-800)',
                900: 'var(--color-text-green-900)',
            },
            blue: {
                50: 'var(--color-text-blue-50)',
                100: 'var(--color-text-blue-100)',
                200: 'var(--color-text-blue-200)',
                300: 'var(--color-text-blue-300)',
                400: 'var(--color-text-blue-400)',
                500: 'var(--color-text-blue-500)',
                600: 'var(--color-text-blue-600)',
                700: 'var(--color-text-blue-700)',
                800: 'var(--color-text-blue-800)',
                900: 'var(--color-text-blue-900)',
            },
            indigo: {
                50: 'var(--color-text-indigo-50)',
                100: 'var(--color-text-indigo-100)',
                200: 'var(--color-text-indigo-200)',
                300: 'var(--color-text-indigo-300)',
                400: 'var(--color-text-indigo-400)',
                500: 'var(--color-text-indigo-500)',
                600: 'var(--color-text-indigo-600)',
                700: 'var(--color-text-indigo-700)',
                800: 'var(--color-text-indigo-800)',
                900: 'var(--color-text-indigo-900)',
            },
            purple: {
                50: 'var(--color-text-purple-50)',
                100: 'var(--color-text-purple-100)',
                200: 'var(--color-text-purple-200)',
                300: 'var(--color-text-purple-300)',
                400: 'var(--color-text-purple-400)',
                500: 'var(--color-text-purple-500)',
                600: 'var(--color-text-purple-600)',
                700: 'var(--color-text-purple-700)',
                800: 'var(--color-text-purple-800)',
                900: 'var(--color-text-purple-900)',
            },
            pink: {
                50: 'var(--color-text-pink-50)',
                100: 'var(--color-text-pink-100)',
                200: 'var(--color-text-pink-200)',
                300: 'var(--color-text-pink-300)',
                400: 'var(--color-text-pink-400)',
                500: 'var(--color-text-pink-500)',
                600: 'var(--color-text-pink-600)',
                700: 'var(--color-text-pink-700)',
                800: 'var(--color-text-pink-800)',
                900: 'var(--color-text-pink-900)',
            },
        },
        backgroundColor: {
            white: 'var(--color-bg-white)',
            gray: {
                50: 'var(--color-bg-gray-50)',
                100: 'var(--color-bg-gray-100)',
                200: 'var(--color-bg-gray-200)',
                300: 'var(--color-bg-gray-300)',
                400: 'var(--color-bg-gray-400)',
                500: 'var(--color-bg-gray-500)',
                600: 'var(--color-bg-gray-600)',
                700: 'var(--color-bg-gray-700)',
                800: 'var(--color-bg-gray-800)',
                900: 'var(--color-bg-gray-900)',
            },
            red: {
                50: 'var(--color-bg-red-50)',
                100: 'var(--color-bg-red-100)',
                200: 'var(--color-bg-red-200)',
                300: 'var(--color-bg-red-300)',
                400: 'var(--color-bg-red-400)',
                500: 'var(--color-bg-red-500)',
                600: 'var(--color-bg-red-600)',
                700: 'var(--color-bg-red-700)',
                800: 'var(--color-bg-red-800)',
                900: 'var(--color-bg-red-900)',
            },
            yellow: {
                50: 'var(--color-bg-yellow-50)',
                100: 'var(--color-bg-yellow-100)',
                200: 'var(--color-bg-yellow-200)',
                300: 'var(--color-bg-yellow-300)',
                400: 'var(--color-bg-yellow-400)',
                500: 'var(--color-bg-yellow-500)',
                600: 'var(--color-bg-yellow-600)',
                700: 'var(--color-bg-yellow-700)',
                800: 'var(--color-bg-yellow-800)',
                900: 'var(--color-bg-yellow-900)',
            },
            green: {
                50: 'var(--color-bg-green-50)',
                100: 'var(--color-bg-green-100)',
                200: 'var(--color-bg-green-200)',
                300: 'var(--color-bg-green-300)',
                400: 'var(--color-bg-green-400)',
                500: 'var(--color-bg-green-500)',
                600: 'var(--color-bg-green-600)',
                700: 'var(--color-bg-green-700)',
                800: 'var(--color-bg-green-800)',
                900: 'var(--color-bg-green-900)',
            },
            blue: {
                50: 'var(--color-bg-blue-50)',
                100: 'var(--color-bg-blue-100)',
                200: 'var(--color-bg-blue-200)',
                300: 'var(--color-bg-blue-300)',
                400: 'var(--color-bg-blue-400)',
                500: 'var(--color-bg-blue-500)',
                600: 'var(--color-bg-blue-600)',
                700: 'var(--color-bg-blue-700)',
                800: 'var(--color-bg-blue-800)',
                900: 'var(--color-bg-blue-900)',
            },
            indigo: {
                50: 'var(--color-bg-indigo-50)',
                100: 'var(--color-bg-indigo-100)',
                200: 'var(--color-bg-indigo-200)',
                300: 'var(--color-bg-indigo-300)',
                400: 'var(--color-bg-indigo-400)',
                500: 'var(--color-bg-indigo-500)',
                600: 'var(--color-bg-indigo-600)',
                700: 'var(--color-bg-indigo-700)',
                800: 'var(--color-bg-indigo-800)',
                900: 'var(--color-bg-indigo-900)',
            },
            purple: {
                50: 'var(--color-bg-purple-50)',
                100: 'var(--color-bg-purple-100)',
                200: 'var(--color-bg-purple-200)',
                300: 'var(--color-bg-purple-300)',
                400: 'var(--color-bg-purple-400)',
                500: 'var(--color-bg-purple-500)',
                600: 'var(--color-bg-purple-600)',
                700: 'var(--color-bg-purple-700)',
                800: 'var(--color-bg-purple-800)',
                900: 'var(--color-bg-purple-900)',
            },
            pink: {
                50: 'var(--color-bg-pink-50)',
                100: 'var(--color-bg-pink-100)',
                200: 'var(--color-bg-pink-200)',
                300: 'var(--color-bg-pink-300)',
                400: 'var(--color-bg-pink-400)',
                500: 'var(--color-bg-pink-500)',
                600: 'var(--color-bg-pink-600)',
                700: 'var(--color-bg-pink-700)',
                800: 'var(--color-bg-pink-800)',
                900: 'var(--color-bg-pink-900)',
            },
        },
        fontFamily: {
            display: 'var(--font-display)',
            body: 'var(--font-body)',
        },
    },
    variants: {},
    plugins: [],
};